# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('join_id', models.ManyToManyField(blank=True, null=True, related_name='joined_user', to='login.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='join_id',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
