# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170224_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dest_stand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
